
export const fontMap: { [key: string]: { name: string, variable: string, url: string, className: string } } = {
    'Inter': {
        name: 'Inter',
        variable: `'Inter', sans-serif`,
        url: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap',
        className: 'font-body',
    },
    'Space Grotesk': {
        name: 'Space Grotesk',
        variable: `'Space Grotesk', sans-serif`,
        url: 'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&display=swap',
        className: 'font-headline',
    },
    'Roboto': {
        name: 'Roboto',
        variable: `'Roboto', sans-serif`,
        url: 'https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap',
        className: 'font-body',
    },
    'Montserrat': {
        name: 'Montserrat',
        variable: `'Montserrat', sans-serif`,
        url: 'https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap',
        className: 'font-body',
    },
     'Lato': {
        name: 'Lato',
        variable: `'Lato', sans-serif`,
        url: 'https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap',
        className: 'font-body',
    },
    'Oswald': {
        name: 'Oswald',
        variable: `'Oswald', sans-serif`,
        url: 'https://fonts.googleapis.com/css2?family=Oswald:wght@400;500;600;700&display=swap',
        className: 'font-headline',
    },
     'Source Code Pro': {
        name: 'Source Code Pro',
        variable: `'Source Code Pro', monospace`,
        url: 'https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500;600;700&display=swap',
        className: 'font-code',
    },
    'Poppins': {
        name: 'Poppins',
        variable: `'Poppins', sans-serif`,
        url: 'https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap',
        className: 'font-body',
    },
    'Nunito': {
        name: 'Nunito',
        variable: `'Nunito', sans-serif`,
        url: 'https://fonts.googleapis.com/css2?family=Nunito:wght@400;500;600;700&display=swap',
        className: 'font-body',
    },
    'Playfair Display': {
        name: 'Playfair Display',
        variable: `'Playfair Display', serif`,
        url: 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;600;700&display=swap',
        className: 'font-headline',
    },
    'Merriweather': {
        name: 'Merriweather',
        variable: `'Merriweather', serif`,
        url: 'https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap',
        className: 'font-body',
    },
    'Roboto Mono': {
        name: 'Roboto Mono',
        variable: `'Roboto Mono', monospace`,
        url: 'https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@400;500;700&display=swap',
        className: 'font-code',
    },
    'Ubuntu': {
        name: 'Ubuntu',
        variable: `'Ubuntu', sans-serif`,
        url: 'https://fonts.googleapis.com/css2?family=Ubuntu:wght@400;500;700&display=swap',
        className: 'font-body',
    },
    'Exo 2': {
        name: 'Exo 2',
        variable: `'Exo 2', sans-serif`,
        url: 'https://fonts.googleapis.com/css2?family=Exo+2:wght@400;500;600;700&display=swap',
        className: 'font-headline',
    },
    'Fira Sans': {
        name: 'Fira Sans',
        variable: `'Fira Sans', sans-serif`,
        url: 'https://fonts.googleapis.com/css2?family=Fira+Sans:wght@400;500;700&display=swap',
        className: 'font-body',
    },
    'Quicksand': {
        name: 'Quicksand',
        variable: `'Quicksand', sans-serif`,
        url: 'https://fonts.googleapis.com/css2?family=Quicksand:wght@400;500;600;700&display=swap',
        className: 'font-body',
    },
    'Josefin Sans': {
        name: 'Josefin Sans',
        variable: `'Josefin Sans', sans-serif`,
        url: 'https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@400;500;600;700&display=swap',
        className: 'font-headline',
    },
    'Cormorant Garamond': {
        name: 'Cormorant Garamond',
        variable: `'Cormorant Garamond', serif`,
        url: 'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;500;600;700&display=swap',
        className: 'font-headline',
    },
    'IBM Plex Mono': {
        name: 'IBM Plex Mono',
        variable: `'IBM Plex Mono', monospace`,
        url: 'https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;700&display=swap',
        className: 'font-code',
    },
     'DM Sans': {
        name: 'DM Sans',
        variable: `'DM Sans', sans-serif`,
        url: 'https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap',
        className: 'font-body',
    },
    'Anton': {
        name: 'Anton',
        variable: `'Anton', sans-serif`,
        url: 'https://fonts.googleapis.com/css2?family=Anton&display=swap',
        className: 'font-headline',
    },
    'Bebas Neue': {
        name: 'Bebas Neue',
        variable: `'Bebas Neue', sans-serif`,
        url: 'https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap',
        className: 'font-headline',
    }
};
